// Fetch self-hosted latin woff2 subsets for the brand fonts (M4e). Run once;
// outputs to public/fonts/ + public/fonts/fonts.css. Removes the render-blocking
// Google Fonts request and any third-party round-trip / font-swap CLS risk.
//   node scripts/fetch-fonts.mjs
import { mkdirSync, writeFileSync } from 'node:fs';
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17 Safari/605.1.15';
const families = [
  'Instrument+Sans:wght@400;500;600;700',
  'IBM+Plex+Mono:wght@400;500',
];
mkdirSync(new URL('../public/fonts/', import.meta.url), { recursive: true });
let out = '/* Self-hosted brand fonts (latin subset), generated by scripts/fetch-fonts.mjs */\n';
for (const fam of families) {
  const css = await (await fetch(`https://fonts.googleapis.com/css2?family=${fam}&display=swap`, { headers: { 'User-Agent': UA } })).text();
  // keep only the `/* latin */` @font-face blocks
  const blocks = css.split('@font-face').slice(1);
  for (const b of blocks) {
    const comment = css.slice(0, css.indexOf('@font-face' + b));
    // determine subset from the comment immediately preceding this block
  }
  // simpler: regex over comment+block pairs
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g;
  let m;
  while ((m = re.exec(css))) {
    if (m[1] !== 'latin') continue;
    const body = m[2];
    const famName = (body.match(/font-family:\s*'([^']+)'/) || [])[1];
    const weight = (body.match(/font-weight:\s*(\d+)/) || [])[1];
    const url = (body.match(/url\(([^)]+\.woff2)\)/) || [])[1];
    if (!url) continue;
    const slug = famName.toLowerCase().replace(/\s+/g, '-') + '-' + weight;
    const file = `${slug}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    writeFileSync(new URL(`../public/fonts/${file}`, import.meta.url), buf);
    out += `@font-face{font-family:'${famName}';font-style:normal;font-weight:${weight};font-display:swap;src:url('/insightout/fonts/${file}') format('woff2');}\n`;
    console.log('fetched', file, buf.length, 'bytes');
  }
}
writeFileSync(new URL('../public/fonts/fonts.css', import.meta.url), out);
console.log('wrote public/fonts/fonts.css');
